In [3]:
import numpy as np
from sklearn.tree import DecisionTreeClassifier, export_text
from sklearn.metrics import accuracy_score, confusion_matrix
from sklearn.model_selection import train_test_split

X = np.array([
    [20, 4], [22, 5], [25, 6],
    [30, 10], [32, 12], [35, 14],
    [40, 18], [45, 20], [48, 22],
    [52, 25], [55, 28], [60, 30],
    [62, 32], [65, 35], [70, 40],
    [30, 10], [45, 20], [60, 30],
    [18, 3], [21, 4], [24, 5],
    [28, 9], [33, 11], [36, 15],
    [25, 6], [55, 28], [40, 18],
    [68, 38], [72, 42], [66, 36]
])

y = np.array([
    "cat", "cat", "cat",
    "dog", "dog", "dog",
    "dog", "dog", "dog",
    "horse", "horse", "horse",
    "horse", "horse", "horse",
    "cat", "horse", "dog",
    "cat", "cat", "cat",
    "dog", "dog", "dog",
    "dog", "dog", "horse",
    "horse", "horse", "horse"
])

splits = [0.2, 0.3, 0.4]  # test_size values for 80/20, 70/30, 60/40

for test_size in splits:
    print("\n" + "="*70)
    print(f"Train/Test split: {int((1-test_size)*100)}/{int(test_size*100)}")

    # Use stratify=y to keep class balance similar in train/test
    X_train, X_test, y_train, y_test = train_test_split(
        X, y, test_size=test_size, random_state=42, stratify=y
    )

    clf = DecisionTreeClassifier(random_state=42)
    clf.fit(X_train, y_train)

    y_pred = clf.predict(X_test)

    acc = accuracy_score(y_test, y_pred)
    cm = confusion_matrix(y_test, y_pred, labels=["cat", "dog", "horse"])

    print(f"Accuracy: {acc:.4f}")
    print("Confusion Matrix (rows=true, cols=pred) for labels [cat, dog, horse]:")
    print(cm)

    rules = export_text(clf, feature_names=["Size", "Weight"])
    print("\nTree rules:")
    print(rules)

    # Task 5: Predict [34, 17] using the trained model of this split
    sample = np.array([[34, 17]])
    sample_pred = clf.predict(sample)[0]
    print(f"Prediction for [34, 17]: {sample_pred}")

print("\n" + "="*70)
print("Comparison note:")
print("80/20: More train, less test")
print("- With less training data (60/40) results can vary more, but evaluation is on more test samples.")


Train/Test split: 80/20
Accuracy: 0.3333
Confusion Matrix (rows=true, cols=pred) for labels [cat, dog, horse]:
[[1 1 0]
 [0 0 2]
 [0 1 1]]

Tree rules:
|--- Size <= 38.00
|   |--- Weight <= 7.50
|   |   |--- Weight <= 5.50
|   |   |   |--- class: cat
|   |   |--- Weight >  5.50
|   |   |   |--- class: cat
|   |--- Weight >  7.50
|   |   |--- class: dog
|--- Size >  38.00
|   |--- Size <= 57.50
|   |   |--- Weight <= 26.50
|   |   |   |--- Weight <= 23.50
|   |   |   |   |--- Weight <= 21.00
|   |   |   |   |   |--- Size <= 42.50
|   |   |   |   |   |   |--- class: dog
|   |   |   |   |   |--- Size >  42.50
|   |   |   |   |   |   |--- class: horse
|   |   |   |   |--- Weight >  21.00
|   |   |   |   |   |--- class: dog
|   |   |   |--- Weight >  23.50
|   |   |   |   |--- class: horse
|   |   |--- Weight >  26.50
|   |   |   |--- class: dog
|   |--- Size >  57.50
|   |   |--- class: horse

Prediction for [34, 17]: dog

Train/Test split: 70/30
Accuracy: 0.4444
Confusion Matrix (rows=tr

In [4]:
import numpy as np
from sklearn.tree import DecisionTreeClassifier, export_text
from sklearn.metrics import accuracy_score, confusion_matrix
from sklearn.model_selection import train_test_split

# Dataset from homework
X = np.array([
    [20,4],[22,5],[25,6],[30,10],[32,12],[35,14],[40,18],[45,20],[48,22],
    [52,25],[55,28],[60,30],[62,32],[65,35],[70,40],[30,10],[45,20],[60,30],
    [18,3],[21,4],[24,5],[28,9],[33,11],[36,15],[25,6],[55,28],[40,18],
    [68,38],[72,42],[66,36]
])
y = np.array([
    "cat","cat","cat","dog","dog","dog","dog","dog","dog","horse","horse","horse",
    "horse","horse","horse","cat","horse","dog","cat","cat","cat","dog","dog",
    "dog","dog","dog","horse","horse","horse","horse"
])

# Test splits: 80/20, 70/30, 60/40
splits = [(0.8, 0.2), (0.7, 0.3), (0.6, 0.4)]
results = {}

for train_size, test_size in splits:
    X_train, X_test, y_train, y_test = train_test_split(
        X, y, train_size=train_size, test_size=test_size, 
        random_state=42, stratify=y
    )
    
    # Train Decision Tree
    clf = DecisionTreeClassifier(random_state=42)
    clf.fit(X_train, y_train)
    y_pred = clf.predict(X_test)
    
    # Metrics
    accuracy = accuracy_score(y_test, y_pred)
    cm = confusion_matrix(y_test, y_pred, labels=['cat', 'dog', 'horse'])
    rules = export_text(clf, feature_names=['Size', 'Weight'])
    
    key = f"{int(train_size*100)}/{int(test_size*100)}"
    results[key] = {
        'accuracy': accuracy, 
        'confusion_matrix': cm.tolist(), 
        'rules': rules
    }
    
    print(f"\n=== {key} Split ===")
    print(f"Accuracy: {accuracy:.3f}")
    print("Confusion Matrix:")
    print(cm)
    print("\nDecision Rules:")
    print(rules)

# Predict new animal [34, 17]
new_animal = np.array([[34, 17]])
final_pred = clf.predict(new_animal)
print(f"\nPrediction for [34,17]: {final_pred[0]}")



=== 80/20 Split ===
Accuracy: 0.333
Confusion Matrix:
[[1 1 0]
 [0 0 2]
 [0 1 1]]

Decision Rules:
|--- Size <= 38.00
|   |--- Weight <= 7.50
|   |   |--- Weight <= 5.50
|   |   |   |--- class: cat
|   |   |--- Weight >  5.50
|   |   |   |--- class: cat
|   |--- Weight >  7.50
|   |   |--- class: dog
|--- Size >  38.00
|   |--- Size <= 57.50
|   |   |--- Weight <= 26.50
|   |   |   |--- Weight <= 23.50
|   |   |   |   |--- Weight <= 21.00
|   |   |   |   |   |--- Size <= 42.50
|   |   |   |   |   |   |--- class: dog
|   |   |   |   |   |--- Size >  42.50
|   |   |   |   |   |   |--- class: horse
|   |   |   |   |--- Weight >  21.00
|   |   |   |   |   |--- class: dog
|   |   |   |--- Weight >  23.50
|   |   |   |   |--- class: horse
|   |   |--- Weight >  26.50
|   |   |   |--- class: dog
|   |--- Size >  57.50
|   |   |--- class: horse


=== 70/30 Split ===
Accuracy: 0.444
Confusion Matrix:
[[1 1 0]
 [0 2 2]
 [0 2 1]]

Decision Rules:
|--- Size <= 42.50
|   |--- Weight <= 7.50
|   | 